Fixed issue in mojang/api/auth/security.py